# Generated by Django 6.0.4 on 2026-04-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.CharField(max_length=50)),
                ('is_open', models.BooleanField(default=True)),
                ('emoji', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_organic', models.BooleanField(default=False)),
                ('emoji', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=6)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shop')),
            ],
        ),
    ]
